### PR TITLE
add --ignore-ssl-errors flag to the queries

### PR DESCRIPTION
**Pull request by vmatiyko**
There are SSL handshake failures that appear for some pages, so this tiny PR has to fix it.

### CODE REVIEW

**Comment by sergey-alekseev** [comment]
@micmro this is a problem we encountered with quite many URLs. Let us know if you want @vmatiyko to add more info.

**Comment by micmro** [comment]
Thanks for the contribution! What exactly is the problem - do you try to access sites with self-signed certs?

**Comment by sergey-alekseev** [comment]
@vmatiyko will provide more details.

**Comment by vmatiyko** [comment]
@micmro There are a few examples:
When I run PhantomJS in the following way with the next websites:
```
./node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs stylify-crawler.js  "https://www.comfortlining.com/"
```

or:
```
./node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs stylify-crawler.js "https://www.mushroomjerky.com"
```

it responds: `ERROR(404)`.

The output with `--debug=true` flag:
```
2022-01-03T19:34:42 [DEBUG] CookieJar - Created but will not store cookies (use option '--cookies-file=<filename>' to enable persistent cookie storage)
2022-01-03T19:34:42 [DEBUG] Set  "http"  proxy to:  "" : 1080
2022-01-03T19:34:42 [DEBUG] Phantom - execute: Configuration
2022-01-03T19:34:42 [DEBUG]      0 objectName : ""
2022-01-03T19:34:42 [DEBUG]      1 cookiesFile : ""
2022-01-03T19:34:42 [DEBUG]      2 diskCacheEnabled : "false"
2022-01-03T19:34:42 [DEBUG]      3 maxDiskCacheSize : "-1"
2022-01-03T19:34:42 [DEBUG]      4 diskCachePath : ""
2022-01-03T19:34:42 [DEBUG]      5 ignoreSslErrors : "false"
2022-01-03T19:34:42 [DEBUG]      6 localUrlAccessEnabled : "true"
2022-01-03T19:34:42 [DEBUG]      7 localToRemoteUrlAccessEnabled : "false"
2022-01-03T19:34:42 [DEBUG]      8 outputEncoding : "UTF-8"
2022-01-03T19:34:42 [DEBUG]      9 proxyType : "http"
2022-01-03T19:34:42 [DEBUG]      10 proxy : ":1080"
2022-01-03T19:34:42 [DEBUG]      11 proxyAuth : ":"
2022-01-03T19:34:42 [DEBUG]      12 scriptEncoding : "UTF-8"
2022-01-03T19:34:42 [DEBUG]      13 webSecurityEnabled : "true"
2022-01-03T19:34:42 [DEBUG]      14 offlineStoragePath : ""
2022-01-03T19:34:42 [DEBUG]      15 localStoragePath : ""
2022-01-03T19:34:42 [DEBUG]      16 localStorageDefaultQuota : "-1"
2022-01-03T19:34:42 [DEBUG]      17 offlineStorageDefaultQuota : "-1"
2022-01-03T19:34:42 [DEBUG]      18 printDebugMessages : "true"
2022-01-03T19:34:42 [DEBUG]      19 javascriptCanOpenWindows : "true"
2022-01-03T19:34:42 [DEBUG]      20 javascriptCanCloseWindows : "true"
2022-01-03T19:34:42 [DEBUG]      21 sslProtocol : "default"
2022-01-03T19:34:42 [DEBUG]      23 sslCertificatesPath : ""
2022-01-03T19:34:42 [DEBUG]      24 sslClientCertificateFile : ""
2022-01-03T19:34:42 [DEBUG]      25 sslClientKeyFile : ""
2022-01-03T19:34:42 [DEBUG]      26 sslClientKeyPassphrase : ""
2022-01-03T19:34:42 [DEBUG]      27 webdriver : ":"
2022-01-03T19:34:42 [DEBUG]      28 webdriverLogFile : ""
2022-01-03T19:34:42 [DEBUG]      29 webdriverLogLevel : "INFO"
2022-01-03T19:34:42 [DEBUG]      30 webdriverSeleniumGridHub : ""
2022-01-03T19:34:42 [DEBUG] Phantom - execute: Script & Arguments
2022-01-03T19:34:42 [DEBUG]      script: "stylify-crawler.js"
2022-01-03T19:34:42 [DEBUG]      0 arg: "https://www.comfortlining.com/"
2022-01-03T19:34:42 [DEBUG] Phantom - execute: Starting normal mode
2022-01-03T19:34:42 [DEBUG] WebPage - setupFrame ""
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] WebPage - updateLoadingProgress: 10
2022-01-03T19:34:42 [DEBUG] Network - SSL Error: "The certificate has expired"
2022-01-03T19:34:42 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(SslHandshakeFailedError) ( "SSL handshake failed" ) URL: "https://www.comfortlining.com/"
2022-01-03T19:34:42 [DEBUG] WebPage - updateLoadingProgress: 100
ERROR(404)
2022-01-03T19:34:42 [DEBUG] WebPage - updateLoadingProgress: 10
2022-01-03T19:34:42 [DEBUG] WebPage - updateLoadingProgress: 100
2022-01-03T19:34:42 [DEBUG] WebPage - setupFrame ""
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] WebPage - updateLoadingProgress: 10
2022-01-03T19:34:42 [DEBUG] WebPage - setupFrame ""
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2022-01-03T19:34:42 [DEBUG] WebPage - updateLoadingProgress: 100
2022-01-03T19:34:42 [DEBUG] WebPage - setupFrame ""
2022-01-03T19:34:42 [DEBUG] WebPage - setupFrame ""
```

So I guess the problem is:
```
2022-01-03T19:34:42 [DEBUG] Network - SSL Error: "The certificate has expired"
2022-01-03T19:34:42 [DEBUG] Network - Resource request error: QNetworkReply::NetworkError(SslHandshakeFailedError) ( "SSL handshake failed" ) URL: "https://www.comfortlining.com/"
```

because if I run PhantomJS with `--ignore-ssl-errors=true` for these websites then it responds in the right way.

**Pull request merged**
